<?php
defined( 'ABSPATH' ) || exit;

class Mavo_Header_Slider {

	// Pre-sized 360 px wide logo (WebP, already generated by WordPress)
	private const LOGO_PATH = 'uploads/2026/03/3verres1bib_banner2-360x.webp';

	// Language-specific subtitles
	private const SUBTITLES = [
		'fr' => 'Plus de 180 voyages avec nos enfants',
		'de' => 'Über 180 Familienreisen',
		'en' => 'Over 180 family trips with our kids',
	];

	/**
	 * Accessible name for the two home links.
	 *
	 * Both were hardcoded as "Maman Voyage – accueil" while the subtitle three
	 * lines above was already translated, so English and German screen-reader
	 * users were read the French word for "home".
	 */
	private const HOME_LABELS = [
		'fr' => 'Maman Voyage – accueil',
		'de' => 'Maman Voyage – Startseite',
		'en' => 'Maman Voyage – home',
	];

	public static function render(): string {
		$lang       = mavo_current_language();
		$home_url   = mavo_home_url();
		$logo_url   = content_url( self::LOGO_PATH );
		$subtitle   = self::SUBTITLES[ $lang ] ?? self::SUBTITLES['fr'];
		$home_label = self::HOME_LABELS[ $lang ] ?? self::HOME_LABELS['fr'];

		ob_start();
		?>
		<div class="mavo-slider mavo-slider--header" data-interval="3000"
		     role="region" aria-label="Maman Voyage">
			<div class="mavo-slider__track">

				<div class="mavo-slider__slide">
					<a href="<?php echo esc_url( $home_url ); ?>" class="mavo-slide__link"
					   aria-label="<?php echo esc_attr( $home_label ); ?>">
						<img src="<?php echo esc_url( $logo_url ); ?>"
						     alt="Maman Voyage"
						     width="360" height="100"
						     loading="eager"
						     fetchpriority="high">
					</a>
				</div>

				<div class="mavo-slider__slide mavo-slide--text">
					<a href="<?php echo esc_url( $home_url ); ?>" class="mavo-slide__link"
					   aria-label="<?php echo esc_attr( $home_label ); ?>">
						<p class="mavo-slide__title">Maman Voyage</p>
						<p class="mavo-slide__subtitle"><?php echo esc_html( $subtitle ); ?></p>
					</a>
				</div>

			</div>
		</div>
		<?php
		return ob_get_clean();
	}
}
