<?php
defined( 'ABSPATH' ) || exit;

class Mavo_Header_Slider {

	// Pre-sized 360 px wide logo (WebP, already generated by WordPress)
	private const LOGO_PATH = 'uploads/2026/03/3verres1bib_banner2-360x.webp';

	// Language-specific subtitles
	private const SUBTITLES = [
		'fr' => 'Plus de 180 voyages avec enfants et un tour du monde',
		'de' => 'Über 180 Touren mit den Kindern und eine Weltreise',
		'en' => 'Over 180 family trips with our kids and a world tour',
	];

	public static function render(): string {
		$lang     = mavo_current_language();
		$home_url = mavo_home_url();
		$logo_url = content_url( self::LOGO_PATH );
		$subtitle = self::SUBTITLES[ $lang ] ?? self::SUBTITLES['fr'];

		ob_start();
		?>
		<div class="mavo-slider mavo-slider--header" data-interval="3000"
		     role="region" aria-label="Maman Voyage">
			<div class="mavo-slider__track">

				<div class="mavo-slider__slide">
					<a href="<?php echo esc_url( $home_url ); ?>" class="mavo-slide__link"
					   aria-label="Maman Voyage – accueil">
						<img src="<?php echo esc_url( $logo_url ); ?>"
						     alt="Maman Voyage"
						     width="360" height="100"
						     loading="eager"
						     fetchpriority="high">
					</a>
				</div>

				<div class="mavo-slider__slide mavo-slide--text">
					<a href="<?php echo esc_url( $home_url ); ?>" class="mavo-slide__link"
					   aria-label="Maman Voyage – accueil">
						<p class="mavo-slide__title">Maman Voyage</p>
						<p class="mavo-slide__subtitle"><?php echo esc_html( $subtitle ); ?></p>
					</a>
				</div>

			</div>
		</div>
		<?php
		return ob_get_clean();
	}
}
